name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 4 * * *" # Runs every day at 4am: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

jobs:
  build:
    name: ubuntu-18.04,  Node.js 16.x

    runs-on: ubuntu-18.04
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js "16.x"
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Use Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Build
        shell: bash
        run: |
          yarn

      - name: Checkout Theia
        uses: actions/checkout@master
        with:
          repository: eclipse-theia/theia
          path: ./theia

      - name: Build Theia
        shell: bash
        working-directory: ./theia
        run: |
          yarn --skip-integrity-check --network-timeout 100000
          yarn browser build

      - name: Run Theia
        shell: bash
        working-directory: ./theia
        run: yarn browser start &

      - name: Test (playwright)
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn ui-tests-ci
