name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *" # Runs every day at 4am: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

jobs:
  build:
    name: ubuntu-latest,  Node.js 18.x

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js "18.x"
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Use Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build
        shell: bash
        run: |
          yarn

      - name: Checkout Theia
        uses: actions/checkout@v4
        with:
          repository: eclipse-theia/theia
          path: ./theia

      - name: Build Theia browser example
        shell: bash
        working-directory: ./theia
        run: |
          yarn --skip-integrity-check --network-timeout 100000
          yarn browser build

      - name: Run Theia browser example
        shell: bash
        working-directory: ./theia
        run: yarn browser start &

      - name: Test (playwright)
        shell: bash
        run: yarn ui-tests
